[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
